apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack-ingress
  namespace: localstack
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: localstack.local # Możesz zmienić na własną domenę
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: localstack
            port:
              number: 4566
