apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://localstack.github.io/helm-charts'
    chart: localstack
    targetRevision: 0.6.27
    helm:
      values: |
        localstack:
          pro: true
          authToken: "TUTAJ_WKLEJ_SWOJ_TOKEN_PRO"
        persistence:
          enabled: true
          storageClass: "openebs-hostpath"
          size: 20Gi
        extraEnvVars:
          - name: PERSISTENCE
            value: "1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true